### ISSUE TITLE
Optional way to install on Windows

### ISSUE THREAD

**Issue by kblomqvist** [jsantero/signal-filter-visualizer#1]
1. Install Anaconda 4.2.0 for Windows (Python 3.5 version), https://www.continuum.io/downloads

2. Open Command Prompt and create new conda environment: `conda create -n signals python=3.5 pyqt=5.6 numpy scipy matplotlib`

3. Activate the new environment as instructed by conda: `activate signals`

4. Change your current working directory to your workspace and git clone signal-filter-visualizer: `git clone https://github.com/jsantero/signal-filter-visualizer.git`

5. Install signal-filter-visaulizer (editable): `pip install --process-dependency-links -e signal-filter-visualizer`

**Comment by kblomqvist** [comment]
If I omit `pyqt=5.6` from conda and let pip to install it, I will get the following error `ImportError: No module named 'PyQt5.QtCore'`. Maybe it would be better to remove "PyQt5" from `setup.py`?

**Comment by jsantero** [comment]
Thank you. I tested these instructions and they work. I'll incorporate them to the readme. Also PyQt5 will be removed from setup.py as suggested.
