### ISSUE TITLE
Load file and Signal generator tabs' content reacts strangely to resizing

### ISSUE THREAD

**Issue by telshock** [jsantero/signal-filter-visualizer#3]
When the window gets too small, the fields overlap. Window also has to be quite huge because of unnecessary space between add noise and filter areas.

**Comment by kblomqvist** [comment]
Yep. I had a vision of having an empty desktop like window where you can have _"embedded"_ signal windows. Each signal window would have its own _apply filter_ and _add noise_ areas. This way there wouldn't be a dedicated signal/noise area at all. Signals could be brought in by using upper toolbar (there you could have import file or generate sine etc.) or by dragging and dropping a file into main window area (desktop). Of course when doing that a window would be opened to show the file content. For example, if it's CSV, columns are shown and you select which column to import as a signal. Optionally you should also be able to select x-axis (time vector).

**Comment by jsantero** [comment]
Thanks for comments. I've also noticed the odd behaviour when resizing. Qt can often handle these kinds of things all by itself, but looks like this needs more tinkering. So far the presentation/layout of the program has been low in priority in favor of basic functionality. I'll make the UI better when I know better which kind of functionality I want in the program. I was thinking about making use docking widgets that the user can reposition as he likes.
